### ISSUE TITLE
How to explicitly not create a SAN certificate?

### ISSUE THREAD

**Issue by erikverheij** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#410]
Is it possible to instruct the companion to create one certificate per domain? In our setup it's preferable as we don't want www.example.org to be dependent on the availability of example.com.

```
- VIRTUAL_HOST=www.example.org,example.org,www.example.com,example.com
- LETSENCRYPT_HOST=www.example.org,example.org,www.example.com,example.com
```

**Comment by buchdag** [comment]
Unfortunately no, that's not possible at the moment, but that might be a use case for [the experimental standalone cert feature](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/wiki/Standalone-certificates-(beta)), if you are willing to give it a try.

**Comment by mastef** [comment]
Just came here looking for this 👍  Would be great, so we wouldn't have to have 100 containers with one customer cert each, but one container that can handle 100 domains that have different certs. ( We have a client-side SPA - every client is being served the same read only html content, just on their own domain )

**Comment by buchdag** [comment]
@ivolution643 thanks for spotting that, I've just pushed a version of `dev` [that should take care of it](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/176d98fc5e9ce160a836f1efdb7ebd612e92c49c/app/functions.sh#L41) (it does according to the short test I did).

Don't hesitate to try again with the fixed version and to report back (just wait for the new `dev` tag autobuild to complete on Dockerhub).

**Comment by buchdag** [comment]
Feature added by @SilverFire in #647
