### ISSUE TITLE
Option for Must-Staple/RFC7633

### ISSUE THREAD

**Issue by ruffy91** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#492]
Could you please add an option to request Must-Staple for letsencrypt certificates?
https://scotthelme.co.uk/ocsp-must-staple/

This enforces OCSP-Stapling on the client site and is the final block for working OCSP.
https://blog.mozilla.org/security/2015/11/23/improving-revocation-ocsp-must-staple-and-short-lived-certificates/

**Comment by buchdag** [comment]
Hi.

That's currently not possible as `simp_le` (the ACME client used by this container) does not support this but that will be looked into [when we'll switch to another ACME client](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/319#issuecomment-452515417).

**Comment by buchdag** [comment]
This feature has been implemented, [Instructions are here](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Let's-Encrypt-and-ACME.md#ocsp-stapling).
