### ISSUE TITLE
Support for multiple domains under the same container

### ISSUE THREAD

**Issue by CarlosTorrecillas** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#562]
I'm not sure if this is related to this: https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/57 but I have a container with multiple domains associated (being api.domain1.com, api.domain2.com, api.domain3.com), and today I got the email saying that all three domains are about to expire the certificate. My question is whether that's something we can achieve using this container. It is the first time I use that structure (normally I have 1-to-1 relationship between a container and a domain but this time is different).

What I see in the certs folder is that all certs refer to the first domain's certs (api.domain1.com in this case). Is that normal/valid?

Many thanks!

**Comment by CarlosTorrecillas** [comment]
Actually, reading the email again I can see:

> For details about when we send these emails, please visit https://letsencrypt.org/docs/expiration-emails/. In particular, note that this reminder email is still sent if you've obtained a slightly different certificate by adding or removing names. If you've replaced this certificate with a newer one that covers more or fewer names than the list above, you may be able to ignore this message.

Which is my case because I added api.domain3.com recently. I assume that's why

**Comment by buchdag** [comment]
> What I see in the certs folder is that all certs refer to the first domain's certs (api.domain1.com in this case). Is that normal/valid?

Yes, the container create SAN certificates, ie single certificates that cover multiple domain names. The actual certificate is named after the first domain (referred to as base domain in the code), the rest are symlinks to it.

> Which is my case because I added api.domain3.com recently. I assume that's why

Most probably.

**Comment by MaxNoe** [comment]
How would a config for this look like?

**Comment by Mesqualito** [comment]
Can somebody link to an .env-configuration-file for multiple names (and multiple certificates) for domains which link to one container publishing http/80 or paste an example here? Is a wildcard possible (*.domain.eu covering http://one.domain.eu, https://one.domain.eu, http/https://another.domain.eu, http/https://www.domain.eu, http/https://domain.eu... ) ?

Thanks in advance!

**Comment by buchdag** [comment]
@Mesqualito wildcard certificates aren't supported : https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/issues/319

**Comment by buchdag** [comment]
@maxnoe https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Let's-Encrypt-and-ACME.md#multi-domains-certificates

Inactive issue, closing.
