### ISSUE TITLE
Renew before getting "Let's Encrypt certificate expiration notice for domain ..."

### ISSUE THREAD

**Issue by eihns** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#617]
Is it possible to renew the certs before you get these emails? I didnt found anything usefull as ENV Variables...?

When should it automatic renew it? I start to worry somethings wrong. 

I just get a "2020-02-10 19:07:39,449:INFO:simp_le:1546: Certificates already exist and renewal is not necessary, exiting with status code 1." for every domain. The email tells me its expiring in 10 days - do i have to do anything?

**Comment by fracz** [comment]
IMO it's not normal. It should have been refreshed 1 month before the expiration date (at least this is how it worked previously).

I have also received this notice today and in `nginx-web` container found possibly interesting log entry:

> 2020/02/10 20:52:28 [warn] 9#9: no resolver defined to resolve ocsp.int-x3.letsencrypt.org while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/etc/nginx/certs/xxx.crt"

Isn't it related to the https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/614 ?

**Comment by eihns** [comment]
Oh, okay, crazy bug. 

Ive tried /app/force_renew lets see what happens.

**Comment by fracz** [comment]
If you upgraded the `jrcs/letsencrypt-nginx-proxy-companion` image as suggested there and rebuild all container, it should be working for future renewals.

Check the certificate in the browser. It should have the expiration date 3 months from now.

**Comment by eihns** [comment]
Cant really check the certificate, because i have cloudflare installed on the domains. Upgrading of the docker should be done by watchtower, does this directory mean its working? 
/etc/nginx/certs/accounts/acme-v02.api.letsencrypt.org/

**Comment by fracz** [comment]
According to the discussion in the #614 - yes, it does.

**Comment by buchdag** [comment]
> I have also received this notice today and in `nginx-web` container found possibly interesting log entry:
>
>`2020/02/10 20:52:28 [warn] 9#9: no resolver defined to resolve ocsp.int-x3.letsencrypt.org while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/etc/nginx/certs/xxx.crt"`

@fracz this OCSP issue has nothing to do with the LE companion. More info [here](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/issues/524#issuecomment-477640758).

@eihns [you can check the status of your certs using the LE companion container](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Container-utilities.md#show-certificates-informations).

Are you still encountering an automatic renewal issue ?

**Comment by fracz** [comment]
For me everything is working now.

**Comment by buchdag** [comment]
Glad to ear that 👍 

Closing the issue, then.
