### ISSUE TITLE
x509: certificate is valid for letsencrypt-nginx-proxy-companion, not subdomain.example.com

### ISSUE THREAD

**Issue by adamkdean** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#629]
We're seeing an issue where a service that hits an endpoint a lot has a fairly high number of failed requests with the following message:

> x509: certificate is valid for letsencrypt-nginx-proxy-companion, not subdomain.example.com

Has this been experienced before? Does anyone know what the cause may be?

Happy to help debug with guidance.

**Comment by buchdag** [comment]
> x509: certificate is valid for letsencrypt-nginx-proxy-companion, not subdomain.example.com

This means your client is getting the [default generated certificate](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/blob/f5e6cfc688474d8abae40fb2098f88c0de666721/app/entrypoint.sh#L100-L133) instead of the `subdomain.example.com` certificate.

Have you managed to reproduce the issue reliably or is it intermittent ?

**Comment by adamkdean** [comment]
It seems intermittent, since posting this, we've not seen it again. If we experience it again, I'll get more information and either post it here, or create a new ticket. Thanks for explaining about default generated certs @buchdag.

**Comment by adamkdean** [comment]
Just to follow up on this, I've found that this happens whenever requests hit within the small window where a service is restarted, and thus are unavailable. It would be great if there was a way have two services use the same virtual host & SSL cert at the same time, so that you could bring up one container before shutting the other down. I'll close this ticket now as it seems it's not actually an issue.
