### ISSUE TITLE
Let's Encrypt 2020.02.29 CAA Rechecking Bug

### ISSUE THREAD

**Issue by Blueforcer** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#630]
According to 
https://community.letsencrypt.org/t/2020-02-29-caa-rechecking-bug/114591
most of the certificates are invalid now. Also mine.
How can i force to renew all of them?

Ht container tells me:
Certificates already exist and renewal is not necessary

**Comment by buchdag** [comment]
Hi

https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Container-utilities.md#force-certificates-renewal

**Comment by buchdag** [comment]
Took the liberty to rename your issue in case other people are hit by LE's CAA rechecking bug and have to force renewal of certificates but don't know how to do this.

**Comment by buchdag** [comment]
It's been way more than 90 days since the issue with Let's Encrypt happened so this isn't really relevant anymore, closing.
