### ISSUE TITLE
What LETSENCRYPT_HOST should use for subdomain container?

### ISSUE THREAD

**Issue by ravecat** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#636]
Hello! Thank for guide, but could you clarify current point.

I have some applications on my server. Also I have CAA-record _0 issue “letsencrypt.org”_ for my domain _example.com_.

I want to get certificates for _test1.example.com_, _test2.example.com_, etc.

I see that used for run subdomain containers two env variables - VIRTUAL_HOST and LETSENCRYPT_HOST. 

What is LETSENCRYPT_HOST? Subdomain  _test1.example.com_ or root like _example.com_?

**Comment by OscarKolsrud** [comment]
It should be the domain that the certificate should be issued for. Aka. if you want https on test1.example.com LETSENCRYPT_HOST should be test1.example.com

**Comment by buchdag** [comment]
`VIRTUAL_HOST` control the proxy itself, and `LETSENCRYPT_HOST` control the domains that get a certificate issued for them. Most of the time you'll want them set both to the same value.

So in your case:

```yaml
environment:
  - VIRTUAL_HOST=test1.example.com,test2.example.com
  - LETSENCRYPT_HOST=test1.example.com,test2.example.com
```

If a domain is in the `LETSENCRYPT_HOST` env var, it **MUST** also be in the `VIRTUAL_HOST` env var or the ACME challenge will fail (not entirely sure anymore because of a recent change to the `nginx.tmpl` file that I have yet to test, but do this as a precaution).

**Comment by ravecat** [comment]
@buchdag thank you for answers. I try to rephrase my questions. LETSENCRYPT_HOST depends on my CAA-record _example.com 0 issue "letsencrypt.org"_? Use it `LETSENCRYPT_HOST=test1.example.com`
or
`LETSENCRYPT_HOST=example.com`

Could you clarify about getting certificates if it possible

**Comment by buchdag** [comment]
Hi.

Have you read the doc ?

You CAA record only function is to tell Certificate Authorities like Let's Encrypt which one are allowed to issue certificates for your domain (and its subdomains).

**Comment by iamunadike** [comment]
> `VIRTUAL_HOST` control the proxy itself, and `LETSENCRYPT_HOST` control the domains that get a certificate issued for them. Most of the time you'll want them set both to the same value.
> 
> So in your case:
> 
> ```yaml
> environment:
>   - VIRTUAL_HOST=test1.example.com,test2.example.com
>   - LETSENCRYPT_HOST=test1.example.com,test2.example.com
> ```
> 
> If a domain is in the `LETSENCRYPT_HOST` env var, it **MUST** also be in the `VIRTUAL_HOST` env var or the ACME challenge will fail (not entirely sure anymore because of a recent change to the `nginx.tmpl` file that I have yet to test, but do this as a precaution).

Please when I do docker compose down and up , I dont see the certificate issued for the subdomain I added after pulling the new image Please help . What am i Missing???

**Comment by Coinhexa** [comment]
what happens to www here? do you need to do

```
LETSENCRYPT_HOST=test1.example.com,www.test1.example.com
VIRTUAL_HOST=test1.example.com,www.test1.example.com
```
Does www get any special treatment or do I declare it like any other subdomain?

**Comment by buchdag** [comment]
Hi. You need to declare it like any other subdomains, it does not have any special / automagical treatment.
