### ISSUE TITLE
invalid response from .well-known/acme-challenge

### ISSUE THREAD

**Issue by jasononggo** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#646]
what i have done:
```
accidentally remove monolith-odoo after 9 months of no touch.
move monolith-odoo to different ECS instance [different public ip address]
changing the DNS record to the new ECS instance ip address.
forking Verisage / docker-nginx-letsencrypt-odoo
adding minor environment.sh and edit the docker-compose.yml for internal use.
making sure port 80 and 443 is open.
```

source repository:
```
https://github.com/jasononggo/monolith-odoo
/ nginx:1.16.1
/ jwilder/docker-gen:0.7.3
/ jrcs/letsencrypt-nginx-proxy-companion:v.12.1
/ odoo:13.0
/ postgres:11.7
```

output:
`letsencrypt-nginx-proxy-companion    | 2020-04-20 23:45:28,445:ERROR:simp_le:1396: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v02.api.letsencrypt.org/acme/authz-v3/4082310386, https://acme-v02.api.letsencrypt.org/acme/authz-v3/4082310387`

**Comment by jasononggo** [comment]
false issue.

**Comment by w3nda** [comment]
How did you fix it?

**Comment by enchance** [comment]
@jasonrichdarmawan Yes, what's the code?
