### ISSUE TITLE
HTTPS defaulting to 500?

### ISSUE THREAD

**Issue by Faqahat** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#648]
I recently got my Nginx,letsencrypt setup on docker. I find it odd that the https is defaulting to 500 I have to manually add the location route in HTTPS block. 

![image](https://user-images.githubusercontent.com/12972150/80242019-14baa900-867e-11ea-86f7-76a75341cb95.png)

**Comment by buchdag** [comment]
Hi

Where does this config snippets comes from exactly ?

**Comment by Faqahat** [comment]
> Hi
> 
> Where does this config snippets come from exactly?

The issue resolved on its own. When I created a new container the "https" this configuration was generated. I'm guessing that it was having trouble acquiring the certificate with that domain or maybe with the issuer on that day (maybe rate-limit since I had tried 5-6 times already).
My assumption is while the certificate is being acquired from the issuer it defaults to this config.
