### ISSUE TITLE
How to configure letsencrypt staging?

### ISSUE THREAD

**Issue by johschmitz** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#649]
Is it possible to configure
https://letsencrypt.org/docs/staging-environment/

This is really important for testing because of the rate limits.

**Comment by johschmitz** [comment]
Okay I found it in the wiki, there is a LETSENCRYPT_TEST and a ACME_CA_URI environment variable for that.

**Comment by dd-ssc** [comment]
@johschmitz: A link to the wiki page with that info would be helpful to anyone with the same question.
