### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by pupattan** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#652]
502 Bad Gateway if the nginx config on the docker container is not set properly.
I am keeping config as below 
```
server {
    listen 443;
    location / {
        include uwsgi_params;
        uwsgi_pass unix:///tmp/uwsgi.sock;
    }
}

```
If i am keeping listen  443 ssl, it will required certificate to mentioned. 

> no "ssl_certificate" is defined for the "listen ... ssl" directive 

But certificates are created inside /etc/nginx/certs of docker-letsencrypt-nginx-proxy-companion container. So How would a nginx config for this look like?

**Comment by buchdag** [comment]
Hi.

I don't get what you are trying to accomplish. Were does the config block you quoted comes from ?

**Comment by pupattan** [comment]
My container runs nginx server on start up. i have to set certificates in the nginx config file in the containers. 
Currently i am using --volumes-from docker-letsencrypt-nginx-proxy-companion and use the path /etc/nginx/certs inside the containers to set the certificate.

Do you have any other option to get the certificate inside the individual containers from path /etc/nginx/certs ?

**Comment by pupattan** [comment]
The issue is with nginx-proxy
