### ISSUE TITLE
Can you have multiple subdomains?

### ISSUE THREAD

**Issue by lonnietc** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#670]
Hello,

I am running your proxy system and it seems to be working well, but have a question.

Currently, I am able to set the VIRTUAL_HOST and LETSENCRYPT_HOST

like:

$ docker run --detach \
    --name your-proxied-app \
    --env "VIRTUAL_HOST=subdomain.yourdomain.tld" \
    --env "LETSENCRYPT_HOST=subdomain.yourdomain.tld" \
    nginx

Is it possible to have multiple subdomains answer for the same instance, perhaps like:

$ docker run --detach \
    --name your-proxied-app \
    --env "VIRTUAL_HOST=subdomain.yourdomain.tld, subdomain2.yourdomain.tld" \
    --env "LETSENCRYPT_HOST=subdomain.yourdomain.tld, subdomain2.yourdomain.tld" \
    nginx

Any information would be greatly appreciated.
Thanks in advance

**Comment by dromer** [comment]
yes, exactly like this.

**Comment by buchdag** [comment]
https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Let's-Encrypt-and-ACME.md#multi-domains-certificates
