### ISSUE TITLE
Change Default Email

### ISSUE THREAD

**Issue by wkelton** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#672]
I have been using this for years. Ran into an issue where expiration notices were being sent to the wrong email address. Turns out this was due to #525. I have been using LETSENCRYPT_EMAIL on all my containers and some have different email addresses. However, this is not a strict requirement for me. So I set DEFAULT_EMAIL on the letsencrypt container.

But, since the ACME account already exists with the wrong email address, how do I go about changing it to a different email address?

**Comment by buchdag** [comment]
> since the ACME account already exists with the wrong email address, how do I go about changing it to a different email address?

The easiest would be to simply remove the ACME account from `/etc/nginx/certs/accounts` and let the container re-create it.

**Comment by wkelton** [comment]
I deleted the `directory` directory in `/etc/nginx/certs/accounts` brought the container down (I'm using a volume for the certs) and brought it back up. It did not recreate the account. However, I ran `/app/force_renew` in the container and that did the trick.  Thanks.

**Comment by buchdag** [comment]
You're right, I forgot to mention that accounts will only be created on certificate issuance.

Glad that worked for you 👍
