### ISSUE TITLE
Standalone Certificate not generating for root domain when subdomains for it exist

### ISSUE THREAD

**Issue by Tommsy64** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#674]
I have containers with their LETSENCRYPT_HOST set to `sub.mydomain.com` and I would like to add a standalone certificate `mydomain.com`.

I set up `letsencrypt_user_data` like this:
```
LETSENCRYPT_STANDALONE_CERTS=('id')
LETSENCRYPT_id_HOST=('mydomain.com')
```

It seems that [add_standalone_configuration](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/blob/master/app/functions.sh#L107) is matching the occurrences of `sub.mydomain.com` and running `add_location_configuration "$domain"` instead of generating the standalone config.

**Comment by buchdag** [comment]
Hi.

Could you try pulling `duch/letsencrypt-nginx-proxy-companion:fix-674` to verify that it correctly fixes the bug ?

**Comment by buchdag** [comment]
ping @Tommsy64
