### ISSUE TITLE
Infinite loop when domain is suffixed with dot - 150% cpu + 1 GB ram usage

### ISSUE THREAD

**Issue by blackandred** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#676]
Hi,

I made a typo in the `LETSENCRYPT_HOST` and put "." at the end of the domain name.

```
LETSENCRYPT_HOST: "www.riotkit.org.,riotkit.org"
```

When changed to this version, then issue was resolved:
```
LETSENCRYPT_HOST: "www.riotkit.org,riotkit.org"
```

I just let you know, maybe you can add it to FAQ at least even if it could be related to simp_le.

**Comment by buchdag** [comment]
Thanks for reporting this one.
