### ISSUE TITLE
Companion error (Cannot iterate over null (null))

### ISSUE THREAD

**Issue by Tintwo** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#692]
Hello folks,

I notice today I have an error in my docker logs, from letsencrypt-companion.
Unfortunately I'm unable to say when it started.
I use nginx-proxy and the letsencrypt companion for several years without any issue (as explain in the docs) and I didn't change anything recently.
Some of my certificates need to be renewed and they still didn't. Usually all certificates are renewed before I got expire notice mails from LetsEncrypt.

Here is the error I got in docker logs :
```
letsencrypt          | 2020/09/16 06:03:33 Debounce minTimer fired
letsencrypt          | 2020/09/16 06:03:33 Generated '/app/letsencrypt_service_data' from 13 containers
letsencrypt          | 2020/09/16 06:03:33 Running '/app/signal_le_service'
letsencrypt          | jq: error (at <stdin>:1): Cannot iterate over null (null)
letsencrypt          | 2020/09/16 06:03:33 Error: could not get a nginx-proxy container ID.
letsencrypt          | Sleep for 3600s
```
I understand what is this error, but not what there is behind this error. So I missed something or there is a deeper error.
Hope you can reproduce that problem.
If you need more info, tell me.
Regards

> I don't use jwilder nginx-proxy, I use the neilpang's one (more permissive fork from jwilder).

**Comment by buchdag** [comment]
Hi.

Unfortunately I can't provide support for setups that use a forked component.

Please re-open this issue if you switch back to the upstream version of `nginx-proxy` and the issue persists.
