### ISSUE TITLE
Nmap port scan reveals too much information

### ISSUE THREAD

**Issue by dgleba** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#720]
I have a cloud server running one app and use `nginx-proxy` /  `docker-letsencrypt-nginx-proxy-companion` to serve the app with HTTPS.

Thank you for everyone's efforts on this software. It is great.

When I do a port scan I see more info than I would like to see revealed.

It reveals `nginx 1.19.3`,  `commonName=letsencrypt-nginx-proxy-companion`,  `Not valid after:  2021-11-01T23:11:31` and more.

What can be done to reveal as little as possible about the system?

```
nmap -sC -sV -p1-16129 159.xxx.xx.xxx
Starting Nmap 7.01 ( https://nmap.org ) at 2020-12-02 08:56 EST
Nmap scan report for  ..
Not shown: 16126 filtered ports
PORT    STATE SERVICE  VERSION
22/tcp  open  ssh      OpenSSH 8.2p1 Ubuntu 4ubuntu0.1 (Ubuntu Linux; protocol 2.0)
80/tcp  open  http     nginx 1.19.3
|_http-server-header: nginx/1.19.3
|_http-title: 503 Service Temporarily Unavailable
443/tcp open  ssl/http nginx 1.19.3
|_http-server-header: nginx/1.19.3
|_http-title: 503 Service Temporarily Unavailable
| ssl-cert: Subject: commonName=letsencrypt-nginx-proxy-companion
| Not valid before: 2020-11-01T23:11:31
|_Not valid after:  2021-11-01T23:11:31
Service Info: OS: Linux; CPE: cpe:/o:linux:linux_kernel
Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 127.63 seconds
```

**Comment by buchdag** [comment]
@dgleba replace `/etc/nginx/certs/default.crt` and `/etc/nginx/certs/default.key` with your own default certificate and private key. The container won't replace them.

**Comment by andradedpg** [comment]
@buchdag and @dgleba 
I realize that my certificates created since yesterday has a www.domphonesex.co.uk as a commonName. This have a some crossover with that?

**Comment by buchdag** [comment]
@andradedpg what the hell ??

The default certificate is only used when `nginx-proxy` receives a request with an [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication) corresponding to a host name that isn't currently configured.

**Comment by buchdag** [comment]
Inactive issue, closing.
