### ISSUE TITLE
new stack does not work for me

### ISSUE THREAD

**Issue by stefangweichinger** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#722]
I try to set up a docker-compose stack with nginx-proxy and jrcs/letsencrypt-nginx-proxy-companion

I followed the instructions, checked DNS etc ... and can't find the reason LE times out when trying to fetch the challenge files.

Also followed https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Invalid-authorizations.md 

My stack (relevant services, no db etc):

```
# cat docker-compose.yml 
version: '3'

services:

  app:
    image: nextcloud:latest
    networks:
      - nextcloud_network
    restart: always
    #ports:
    #- 8080:80
    volumes:
      - /mnt/docker-volumes/nextcloud/app:/var/www/html
      - /mnt/nextcloud-data:/var/www/html/data
    environment:
      - MYSQL_HOST=mariadb
      - VIRTUAL_HOST=nc.mycloud.tld
      - LETSENCRYPT_HOST=nc.mycloud.tld
      - LETSENCRYPT_EMAIL=it@mycloud.tld
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - letsencrypt
      - nginx-proxy
      - mariadb

  nginx-proxy:
    image: jwilder/nginx-proxy
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    networks:
      - nextcloud_network
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx_proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./nginx_proxy/html:/usr/share/nginx/html:rw
      - ./nginx_proxy/certs:/etc/nginx/certs:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  letsencrypt:
    #image: jrcs/letsencrypt-nginx-proxy-companion:v1.13.1
    image: jrcs/letsencrypt-nginx-proxy-companion
    networks:
      - nextcloud_network
    depends_on:
      - nginx-proxy
    environment:
      DEBUG: 1
    volumes:
      - ./nginx_proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./nginx_proxy/html:/usr/share/nginx/html:rw
      - ./nginx_proxy/certs:/etc/nginx/certs:rw
      - ./nginx_proxy/acme:/etc/acme.sh
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

# other services: mariadb, db_backup, redis removed here

networks:
  nextcloud_network:

volumes:
  nextcloud:
```

As you see above, I also tried to use your older v1.13.1 already.
I cleared "./nginx_proxy" completely between.

I can "curl http://nc.mycloud.tld/.well-known/acme-challenge/v3KTDxbWy..." successfully from several servers outside.

The nextcloud works fine as well, http-only now, sure, but from clients out of their networks (so the port forwards seem to work).

The debug-messages contain (anonymized):

```
letsencrypt_1  | [Fri Dec  4 12:14:35 CET 2020] errordetail='Fetching http://nc.mycloud.tld/.well-known/acme-challenge/v3KTDxbWyKLr0CTfl0hnEL64wZdpZKuEnUiH4-YSYt4: Timeout during connect (likely firewall problem)'

[..]

letsencrypt_1  | [Fri Dec  4 12:14:36 CET 2020] Here is the curl dump log:
letsencrypt_1  | [Fri Dec  4 12:14:36 CET 2020] == Info:   Trying 21x.11y.3z.aa:80...
letsencrypt_1  | == Info: Connection timed out after 1000 milliseconds
letsencrypt_1  | == Info: Closing connection 0
```

The admins at the customer tell me there is no more geoblocking in place (maybe that's not really true yet).
nc.mycloud.tld has a valid A-record, no AAAA-record, there are no CAA-rules in place.

I don't have any ideas anymore, so I thought to file this as an issue.
Maybe I have a mistake in my stack config, maybe it helps to find another issue somewhere.

Thanks for any help here.

**Comment by stefangweichinger** [comment]
In the meantime I edited my config following https://github.com/buchdag/letsencrypt-nginx-proxy-companion-compose/blob/master/2-containers/compose-v3/environment/docker-compose.yaml

Because I suspected my networking config wrong. But no success so far.

**Comment by buchdag** [comment]
@stefangweichinger could you check if the following work with your second configuration:

1) proxying a vanilla `nginx` container (without HTTPS)
2) getting a LE certificate for this container with the companion

**Comment by stefangweichinger** [comment]
Thanks for the reply.

The customer told me they now noticed LE issues on a second machine (non-docker), so it's very likely a problem in their firewall or security setup somewhere. I am out for the weekend there and won't be able to test on the particular host until monday (for now the port forwardings will be disabled over the weekend). 

I'll report back (and maybe show my compose file, for a check from the guru ;-) ).

**Comment by stefangweichinger** [comment]
In the second machine I see the same problem in the logs. It's a bit outdated and uses "certbot 0.31.0".
The fact that it doesn't work on both machines let's me assume that it's more of a network or DNS issue.

**Comment by buchdag** [comment]
> It's a bit outdated and uses "certbot 0.31.0".

This version is not compatible with ACME v2, and [ACME v1 is being phased out](https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430).

**Comment by stefangweichinger** [comment]
Thanks for the pointer. I will see if I can upgrade that older box (at least to a recent version of certbot) and test again.
But as far as I understand the original issue I filed has nothing to do with ACME v1? Your le-companion uses ACME v2, right? (sure ..)

**Comment by buchdag** [comment]
> But as far as I understand the original issue I filed has nothing to do with ACME v1?
> Your le-companion uses ACME v2, right?

Yup, the original issue does sound like a network / DNS issue to me too.

Don't bother trying with the outdated container as it might hit ACME v1 issues even if the original issue is solved.

**Comment by stefangweichinger** [comment]
> > But as far as I understand the original issue I filed has nothing to do with ACME v1?
> > Your le-companion uses ACME v2, right?
> 
> Yup, the original issue does sound like a network / DNS issue to me too.
> 
> Don't bother trying with the outdated container as it might hit ACME v1 issues even if the original issue is solved.

I understand this as "use `v2.0.0` only from now on" ? ;-)
Does it make any sense to remove the volumes and start over?
I think I have to wait for the customer to check his network/DNS in more detail, yes.

Just for reference (I might have a stupid mistake) here my anonymized compose-file:

```
version: '3'

services:

  app:
    image: nextcloud:latest
    restart: always
    volumes:
      - /mnt/docker-volumes/nextcloud/app:/var/www/html
      - /mnt/nextcloud-data:/var/www/html/data
    environment:
      - MYSQL_HOST=mariadb
      - VIRTUAL_HOST=nextcloud.my.tld
      - LETSENCRYPT_HOST=nextcloud.my.tld
      - LETSENCRYPT_EMAIL=itmanagement@my.tld
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - letsencrypt
      - nginx-proxy
      - mariadb

  mariadb:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - db.env

  db_backup:
    image: selim13/automysqlbackup:2.6-6-debian
    volumes:
      - /mnt/docker-volumes/nextcloud/db_backup:/backup
    environment:
      USERNAME: root
      PASSWORD: "xxyyzz"
      DBHOST: mariadb
      DBEXCLUDE: "performance_schema information_schema"
      CRON_SCHEDULE: "0 0 * * *"
      EXTRA_OPTS: "--single-transaction"
    depends_on:
      - mariadb

  nginx-proxy:
    image: jwilder/nginx-proxy
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx_proxy/conf:/etc/nginx/conf.d
      - ./nginx_proxy/dhparam:/etc/nginx/dhparam
      - ./nginx_proxy/vhost.d:/etc/nginx/vhost.d
      - ./nginx_proxy/html:/usr/share/nginx/html
      - ./nginx_proxy/certs:/etc/nginx/certs:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  letsencrypt:
    #image: jrcs/letsencrypt-nginx-proxy-companion:v1.13.1
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx-proxy
    environment:
      - DEBUG=1
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - ./nginx_proxy/vhost.d:/etc/nginx/vhost.d
      - ./nginx_proxy/html:/usr/share/nginx/html
      - ./nginx_proxy/certs:/etc/nginx/certs
      - ./nginx_proxy/acme:/etc/acme.sh
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  redis:
    image: redis:alpine
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  mariadb:
```



Thanks!

**Comment by buchdag** [comment]
> I understand this as "use v2.0.0 only from now on" ? ;-)

Actually no, that might be a bit misleading but the major version bump of this project does not correspond to the ACME version compatibility. The project has been compatible with ACME v2 since `v1.12` released about a year ago.

And yeah the `v` was dropped from Docker tags starting with `2.0.0` / `2.0`.

**Comment by stefangweichinger** [comment]
Customer decided to fetch a wildcard cert and use that. So I can't debug that further and assume we can close here.
thanks anyway.
