### ISSUE TITLE
CN wrong

### ISSUE THREAD

**Issue by borgdrone7** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#742]
Hi,

I followed the tutorial for setting up proxy companion and I can see in logs that certificates are successfully generated however CN name is instead of my domain actually this string: "letsencrypt-nginx-proxy-companion".
I mapped all folders to volumes as required and added these for the container for which I am generating certificate:
      - VIRTUAL_HOST=mydomain.com
      - LETSENCRYPT_HOST=mydomain.com
      - LETSENCRYPT_EMAIL=email@mydomain.com
I can see folder with name mydomain.com generated in certs and also in acme I can see folder with my email name.
Please note that the same happens even if I am out of test mode. Certificate is again generated and saved correctly but the same issue persists.

What could be the issue?

![letsencrypt-issue](https://user-images.githubusercontent.com/4692377/103181754-cb2df800-48b5-11eb-85f8-0e06b34ae0be.png)

**Comment by buchdag** [comment]
Hi. Could you please follow the repository's bug template, at the very least  **letsencrypt-nginx-proxy-companion image version** and **nginx-proxy-companion configuration** ?

Bug description
-----------------
A clear and concise description of what the bug is.

letsencrypt-nginx-proxy-companion image version
-----------------

Please provide the container version that should be printed to the first line of log at container startup:
```bash
[you@yourhost]: $ docker logs companion-container-name
Info: running letsencrypt-nginx-proxy-companion version v2.0.0
[...]
```

If this first log line isn't present you are using a `v1` image: please provide the [tagged version](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/releases) you are using. If you are using `latest`, please try again with a tagged release before opening an issue (the last `v1` tagged release is `v1.13.1`).

nginx-proxy-companion configuration
-----------------

Please provide the configuration (either command line, compose file, or other) of your nginx-proxy stack and your proxied container(s).

You can obfuscate information you want to keep private (and should obfuscate configuration secrets) such as domain(s) and/or email adress(es), but other than that **please provide the full configurations** and not the just snippets of the parts that seem relevants to you.

Containers logs
-----------------

Please provide the logs of:
- your `letsencrypt-nginx-proxy-companion` container
- your `nginx-proxy` container (or `nginx` and `docker-gen` container in a three containers setup)

`docker logs name-of-the-container`

Docker host
-----------------

 - OS: [e.g. Ubuntu 20.04]
 - Docker version: output of `docker version`

**Comment by buchdag** [comment]
Regarding the certificate with a wrong CN: the companion container [automatically generates a default key and self signed certificate pair](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/pull/423) with `letsencrypt-nginx-proxy-companion` as its `Common Name` for **nginx-proxy** to use. If a requested certificate creation fails for whatever reason (99 % of the time an [ACME authorisation failure](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Invalid-authorizations.md)) the proxy will serve this default certificate instead of the intended one.

**Comment by borgdrone7** [comment]
Hi,

Sorry didn't see the template before. Here is the required info:

letsencrypt-nginx-proxy-companion version:
Info: running letsencrypt-nginx-proxy-companion version v2.0.2-3-ged07a99

letsencrypt-nginx-proxy-companion configuration:
version: '2'

networks:
  default:
    external:
      name: borgdrone7
      
services:
  proxy:
    container_name: proxy_proxy_1
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./certs:/etc/nginx/certs
      - ./params.conf:/etc/nginx/conf.d/params.conf
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    expose:
      - "9000"
    ports:
      - "80:80"
      - "443:443"
  letsencrypt:
    container_name: letsencrypt_1
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme:/etc/acme.sh
    volumes_from:
      - proxy
    environment:
      - DEFAULT_EMAIL=my@email.com
  
current companion log (was very long first time it generated, but everything looked ok, no errors, success messages):

Reloading nginx proxy (73e93a2053d1ff553299847dc7bf3f52958d566e6c2871670ccae87a8219bd22)...
2020/12/27 23:31:28 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
2020/12/27 23:31:28 [notice] 42#42: signal process started
2020/12/27 23:31:28 Generated '/app/letsencrypt_service_data' from 14 containers
2020/12/27 23:31:28 Running '/app/signal_le_service'
2020/12/27 23:31:28 Watching docker events
2020/12/27 23:31:28 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
Reloading nginx proxy (73e93a2053d1ff553299847dc7bf3f52958d566e6c2871670ccae87a8219bd22)...
2020/12/27 23:31:29 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
2020/12/27 23:31:29 [notice] 54#54: signal process started
Creating/renewal mydomain.com certificates... (mydomain.com)
[Sun Dec 27 23:31:30 UTC 2020] Domains not changed.
[Sun Dec 27 23:31:30 UTC 2020] Skip, Next renewal time is: Thu Feb 25 23:29:59 UTC 2021
[Sun Dec 27 23:31:30 UTC 2020] Add '--force' to force to renew.


proxy log:
forego     | starting nginx.1 on port 5000
forego     | starting dockergen.1 on port 5100
dockergen.1 | 2020/12/27 23:31:25 Generated '/etc/nginx/conf.d/default.conf' from 13 containers
dockergen.1 | 2020/12/27 23:31:25 Running 'nginx -s reload'
dockergen.1 | 2020/12/27 23:31:26 Watching docker events
dockergen.1 | 2020/12/27 23:31:26 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
dockergen.1 | 2020/12/27 23:31:26 Received event start for container f469c386cd43
dockergen.1 | 2020/12/27 23:31:26 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'

Os/Docker versions:
Ubuntu 14.04.5 LTS
Docker version 17.05.0-ce, build 89658be

I can delete all certificates and start it again if you want to see the log as it is when it is first generated. I will do it with test set to true as I think I already regenerated 3 times without test and I don't want to be blocked for a week (unless I have to do it without test enabled).

**Comment by buchdag** [comment]
> I can delete all certificates and start it again if you want to see the log as it is when it is first generated. I will do it with test set to true.

Yes please, and yes use the staging endpoint 👍 

Also, please provide the proxied container configuration (compose file).

**Comment by borgdrone7** [comment]
Sure, and thanks for a quick response.

Here is the config from my docker compose:
version: '2'

networks:
  default:
    external:
      name: borgdrone7

services:
  nginx:
    container_name: mysiteweb_nginx_1
    extends:
      file: mysitebase.yml
      service: nginx
    volumes_from:
      - application
    volumes:
      - ~/mysiteweb/docker_prod/config/nginx/upstream/mysiteweb.conf:/etc/nginx/conf.d/upstream.conf
    ports:
      - "8072:80"
    environment:
      - VIRTUAL_HOST=mysite.com
      - LETSENCRYPT_HOST=mysite.com
      - LETSENCRYPT_EMAIL=me@mysite.com
      - LETSENCRYPT_TEST=true
      
      
This is base config from mysitebase.yml:

    nginx:
        build: ./nginx
        volumes:
            - ./config/nginx/common:/etc/nginx/common
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
        expose:
            - "80"
            - "443"


Here is the log from scratch (I replaced my domain with mysite.com):

Info: running letsencrypt-nginx-proxy-companion version v2.0.2-3-ged07a99
Generating a RSA private key
............................................................................................................................................................................................................................................................................................................................................................................................................++++
...........................................................................................................................................................................................++++
writing new private key to '/etc/nginx/certs/default.key.new'
-----
Reloading nginx proxy (20c6aec48c45880da39437685dfbd1554dc96b59cc89be08504d10d2cdfbb272)...
2020/12/28 00:05:31 Generated '/etc/nginx/conf.d/default.conf' from 14 containers
2020/12/28 00:05:31 [notice] 41#41: signal process started
Info: a default key and certificate have been created at /etc/nginx/certs/default.key and /etc/nginx/certs/default.crt.
Info: Creating Diffie-Hellman group in the background.
A pre-generated Diffie-Hellman group will be used for now while the new one is being created.
Generating DH parameters, 2048 bit long safe prime, generator 2
Reloading nginx proxy (20c6aec48c45880da39437685dfbd1554dc96b59cc89be08504d10d2cdfbb272)...
2020/12/28 00:05:32 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
2020/12/28 00:05:32 [notice] 53#53: signal process started
2020/12/28 00:05:32 Generated '/app/letsencrypt_service_data' from 14 containers
2020/12/28 00:05:32 Running '/app/signal_le_service'
2020/12/28 00:05:32 Watching docker events
2020/12/28 00:05:32 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
[Mon Dec 28 00:05:33 UTC 2020] Create account key ok.
[Mon Dec 28 00:05:33 UTC 2020] Registering account: https://acme-v02.api.letsencrypt.org/directory
[Mon Dec 28 00:05:34 UTC 2020] Registered
[Mon Dec 28 00:05:34 UTC 2020] ACCOUNT_THUMBPRINT='q0SZ01RzZZBGqo3mCjQbaeTcFZQaOBFV47ktNc9zsc8'
Reloading nginx proxy (20c6aec48c45880da39437685dfbd1554dc96b59cc89be08504d10d2cdfbb272)...
2020/12/28 00:05:34 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
2020/12/28 00:05:34 [notice] 68#68: signal process started
Creating/renewal mysite.com certificates... (mysite.com)
[Mon Dec 28 00:05:35 UTC 2020] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Mon Dec 28 00:05:35 UTC 2020] Creating domain key
[Mon Dec 28 00:05:36 UTC 2020] The domain key is here: /etc/acme.sh/me@mysite.com/mysite.com/mysite.com.key
[Mon Dec 28 00:05:36 UTC 2020] Single domain='mysite.com'
[Mon Dec 28 00:05:36 UTC 2020] Getting domain auth token for each domain
[Mon Dec 28 00:05:38 UTC 2020] Getting webroot for domain='mysite.com'
[Mon Dec 28 00:05:38 UTC 2020] Verifying: mysite.com
[Mon Dec 28 00:05:41 UTC 2020] Success
[Mon Dec 28 00:05:41 UTC 2020] Verify finished, start to sign.
[Mon Dec 28 00:05:41 UTC 2020] Lets finalize the order.
[Mon Dec 28 00:05:41 UTC 2020] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/107613341/6980302658'
me@ubuntu:~/mysiteweb/docker-proxy$ docker logs letsencrypt_1 
Info: running letsencrypt-nginx-proxy-companion version v2.0.2-3-ged07a99
Generating a RSA private key
............................................................................................................................................................................................................................................................................................................................................................................................................++++
...........................................................................................................................................................................................++++
writing new private key to '/etc/nginx/certs/default.key.new'
-----
Reloading nginx proxy (20c6aec48c45880da39437685dfbd1554dc96b59cc89be08504d10d2cdfbb272)...
2020/12/28 00:05:31 Generated '/etc/nginx/conf.d/default.conf' from 14 containers
2020/12/28 00:05:31 [notice] 41#41: signal process started
Info: a default key and certificate have been created at /etc/nginx/certs/default.key and /etc/nginx/certs/default.crt.
Info: Creating Diffie-Hellman group in the background.
A pre-generated Diffie-Hellman group will be used for now while the new one is being created.
Generating DH parameters, 2048 bit long safe prime, generator 2
Reloading nginx proxy (20c6aec48c45880da39437685dfbd1554dc96b59cc89be08504d10d2cdfbb272)...
2020/12/28 00:05:32 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
2020/12/28 00:05:32 [notice] 53#53: signal process started
2020/12/28 00:05:32 Generated '/app/letsencrypt_service_data' from 14 containers
2020/12/28 00:05:32 Running '/app/signal_le_service'
2020/12/28 00:05:32 Watching docker events
2020/12/28 00:05:32 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
[Mon Dec 28 00:05:33 UTC 2020] Create account key ok.
[Mon Dec 28 00:05:33 UTC 2020] Registering account: https://acme-v02.api.letsencrypt.org/directory
[Mon Dec 28 00:05:34 UTC 2020] Registered
[Mon Dec 28 00:05:34 UTC 2020] ACCOUNT_THUMBPRINT='q0SZ01RzZZBGqo3mCjQbaeTcFZQaOBFV47ktNc9zsc8'
Reloading nginx proxy (20c6aec48c45880da39437685dfbd1554dc96b59cc89be08504d10d2cdfbb272)...
2020/12/28 00:05:34 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
2020/12/28 00:05:34 [notice] 68#68: signal process started
Creating/renewal mysite.com certificates... (mysite.com)
[Mon Dec 28 00:05:35 UTC 2020] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Mon Dec 28 00:05:35 UTC 2020] Creating domain key
[Mon Dec 28 00:05:36 UTC 2020] The domain key is here: /etc/acme.sh/me@mysite.com/mysite.com/mysite.com.key
[Mon Dec 28 00:05:36 UTC 2020] Single domain='mysite.com'
[Mon Dec 28 00:05:36 UTC 2020] Getting domain auth token for each domain
[Mon Dec 28 00:05:38 UTC 2020] Getting webroot for domain='mysite.com'
[Mon Dec 28 00:05:38 UTC 2020] Verifying: mysite.com
[Mon Dec 28 00:05:41 UTC 2020] Success
[Mon Dec 28 00:05:41 UTC 2020] Verify finished, start to sign.
[Mon Dec 28 00:05:41 UTC 2020] Lets finalize the order.
[Mon Dec 28 00:05:41 UTC 2020] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/107613341/6980302658'
[Mon Dec 28 00:05:42 UTC 2020] Downloading cert.
[Mon Dec 28 00:05:42 UTC 2020] Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/04f3c50543607cf0e15c8e01a431ec2aead2'
[Mon Dec 28 00:05:43 UTC 2020] Cert success.
-----BEGIN CERTIFICATE-----
MIIGIDCCBQigAwIBAgISBPPFBUNgfPDhXI4BpDHsKurSMA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yMDEyMjcyMzA1NDJaFw0yMTAzMjcyMzA1NDJaMBgxFjAUBgNVBAMT
DWxhcHBhc29mdC5jb20wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDX
67glCFDu5FUr3Q/dHI3ewIHzY8E16LqiAmmekwuSRCWACMTR4s3Yq4gsvT9yNWUu
mbwt2IblqvEWTENXrxAHbUqwyibse7ttPnHuDFVNHuvKHkrfTwmlY4W67pkuys7+
5+tHMfhHuqgY4N/qwl4VOKKUE0g1hJvEph2/zIrCN0m56ZlvGSfSxCI5fWpZ2KQ5
K9QBM4dg/OEtLcgdHFqBqXrOu0IX3vrZrd+cMGIgm5GiGAiSGgmb7myO6eE58JKS
4LNDdnX2ZYy7SMf5+SklG8GWYpkMuVipUdEh5K318sEZbtodVqbmsIVA/cm8szyw
HHaUlGzVniiIphaTrEHAFTcxL10j+PTMYcpANzWJbYVR31Eko+dm7Vm/8TNH8jR1
0u9+QQcDLkazcsPPfeFP0jcLTA99pOxdqqBlwFk0l2ozqpiwto6liGIaxlCwQbFZ
M0MhtpTYQ4DUXP651U4BEXbij6B4ficKKjQPcpF5D1GQukcrvFgxVbbZ5EHnsLKf
95MmTWMsBQ6RwjVubKkBpoSq84N6jWf9kU8FReC+NmdmVcXtz0R7nZhPC1GIV5Dh
mw9LgL2Qi835Ky2RMjoqeMcISsYiOH3tSq4TwCe0hYkKmqGJ96ZlJuSZhNmKLtxW
yPrWgZNNhv2bq4T+PI2rgPKMyV+j1GSEy2hmymzeBQIDAQABo4ICSDCCAkQwDgYD
VR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNV
HRMBAf8EAjAAMB0GA1UdDgQWBBQ3Ba9ophCENyfMnR+lK8/n8oU0TTAfBgNVHSME
GDAWgBQULrMXt1hWy65QCUDmH6+dixTCxjBVBggrBgEFBQcBAQRJMEcwIQYIKwYB
BQUHMAGGFWh0dHA6Ly9yMy5vLmxlbmNyLm9yZzAiBggrBgEFBQcwAoYWaHR0cDov
L3IzLmkubGVuY3Iub3JnLzAYBgNVHREEETAPgg1sYXBwYXNvZnQuY29tMEwGA1Ud
IARFMEMwCAYGZ4EMAQIBMDcGCysGAQQBgt8TAQEBMCgwJgYIKwYBBQUHAgEWGmh0
dHA6Ly9jcHMubGV0c2VuY3J5cHQub3JnMIIBBAYKKwYBBAHWeQIEAgSB9QSB8gDw
AHcAXNxDkv7mq0VEsV6a1FbmEDf71fpH3KFzlLJe5vbHDsoAAAF2pqo58wAABAMA
SDBGAiEAhlSJKBeGCJbyW5C2xNp9qOw17iTIqhi39BtuwCNSe+UCIQCrORNHg9Ki
eyjyCZtMMqQwLDo6q5JDFuAHH1BhFafo1wB1APZclC/RdzAiFFQYCDCUVo7jTRMZ
M7/fDC8gC8xO8WTjAAABdqaqOtUAAAQDAEYwRAIgVouaZP/0yHwqpKAjHpqYHrWp
5sh4vg+aIAEQ8dGp+H4CIENOD+DE4ABArNeJVWoHEzSVtLArqVvxBuwtY2AeZxqa
MA0GCSqGSIb3DQEBCwUAA4IBAQAoa9N/753I0AmF0prEj1P1VNqxMi6GnTcRbAFE
gC6wnZ1/LC6cBl047/jFmiymfX/h8Z+JyNV6dYobaHZd5bzF1+XDaXOnOeLB0mbF
Xrl52NDRGi+GqKqeMMZgaeqOyKfLlHsh03BYMeTdwBpA9f1bH2Ox4eyTUdW+A2E3
H/5nTZAI6gM/QnI8XBGrp6e+K5cnpdqAFaFqFnP6ec42AFeqsDGfgDsXx7v+Het8
Zq/DXMMdhBj56XzxDDdzLleEooD4vyg2koOR2Id84R8P9EbguQio6mPiv5tK9Dbp
4uNSy7xXUEmkNy9O8AoFgfRDfWFrw+GEuV6hyn7r/zlBitdQ
-----END CERTIFICATE-----
[Mon Dec 28 00:05:43 UTC 2020] Your cert is in  /etc/acme.sh/me@mysite.com/mysite.com/mysite.com.cer 
[Mon Dec 28 00:05:43 UTC 2020] Your cert key is in  /etc/acme.sh/me@mysite.com/mysite.com/mysite.com.key 
[Mon Dec 28 00:05:43 UTC 2020] The intermediate CA cert is in  /etc/acme.sh/me@mysite.com/mysite.com/ca.cer 
[Mon Dec 28 00:05:43 UTC 2020] And the full chain certs is there:  /etc/acme.sh/me@mysite.com/mysite.com/fullchain.cer 
[Mon Dec 28 00:05:43 UTC 2020] Installing cert to:/etc/nginx/certs/mysite.com/cert.pem
[Mon Dec 28 00:05:43 UTC 2020] Installing CA to:/etc/nginx/certs/mysite.com/chain.pem
[Mon Dec 28 00:05:43 UTC 2020] Installing key to:/etc/nginx/certs/mysite.com/key.pem
[Mon Dec 28 00:05:43 UTC 2020] Installing full chain to:/etc/nginx/certs/mysite.com/fullchain.pem
me@ubuntu:~/mysiteweb/docker-proxy$ docker logs letsencrypt_1 
Info: running letsencrypt-nginx-proxy-companion version v2.0.2-3-ged07a99
Generating a RSA private key
............................................................................................................................................................................................................................................................................................................................................................................................................++++
...........................................................................................................................................................................................++++
writing new private key to '/etc/nginx/certs/default.key.new'
-----
Reloading nginx proxy (20c6aec48c45880da39437685dfbd1554dc96b59cc89be08504d10d2cdfbb272)...
2020/12/28 00:05:31 Generated '/etc/nginx/conf.d/default.conf' from 14 containers
2020/12/28 00:05:31 [notice] 41#41: signal process started
Info: a default key and certificate have been created at /etc/nginx/certs/default.key and /etc/nginx/certs/default.crt.
Info: Creating Diffie-Hellman group in the background.
A pre-generated Diffie-Hellman group will be used for now while the new one is being created.
Generating DH parameters, 2048 bit long safe prime, generator 2
Reloading nginx proxy (20c6aec48c45880da39437685dfbd1554dc96b59cc89be08504d10d2cdfbb272)...
2020/12/28 00:05:32 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
2020/12/28 00:05:32 [notice] 53#53: signal process started
2020/12/28 00:05:32 Generated '/app/letsencrypt_service_data' from 14 containers
2020/12/28 00:05:32 Running '/app/signal_le_service'
2020/12/28 00:05:32 Watching docker events
2020/12/28 00:05:32 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
[Mon Dec 28 00:05:33 UTC 2020] Create account key ok.
[Mon Dec 28 00:05:33 UTC 2020] Registering account: https://acme-v02.api.letsencrypt.org/directory
[Mon Dec 28 00:05:34 UTC 2020] Registered
[Mon Dec 28 00:05:34 UTC 2020] ACCOUNT_THUMBPRINT='q0SZ01RzZZBGqo3mCjQbaeTcFZQaOBFV47ktNc9zsc8'
Reloading nginx proxy (20c6aec48c45880da39437685dfbd1554dc96b59cc89be08504d10d2cdfbb272)...
2020/12/28 00:05:34 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
2020/12/28 00:05:34 [notice] 68#68: signal process started
Creating/renewal mysite.com certificates... (mysite.com)
[Mon Dec 28 00:05:35 UTC 2020] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Mon Dec 28 00:05:35 UTC 2020] Creating domain key
[Mon Dec 28 00:05:36 UTC 2020] The domain key is here: /etc/acme.sh/me@mysite.com/mysite.com/mysite.com.key
[Mon Dec 28 00:05:36 UTC 2020] Single domain='mysite.com'
[Mon Dec 28 00:05:36 UTC 2020] Getting domain auth token for each domain
[Mon Dec 28 00:05:38 UTC 2020] Getting webroot for domain='mysite.com'
[Mon Dec 28 00:05:38 UTC 2020] Verifying: mysite.com
[Mon Dec 28 00:05:41 UTC 2020] Success
[Mon Dec 28 00:05:41 UTC 2020] Verify finished, start to sign.
[Mon Dec 28 00:05:41 UTC 2020] Lets finalize the order.
[Mon Dec 28 00:05:41 UTC 2020] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/107613341/6980302658'
[Mon Dec 28 00:05:42 UTC 2020] Downloading cert.
[Mon Dec 28 00:05:42 UTC 2020] Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/04f3c50543607cf0e15c8e01a431ec2aead2'
[Mon Dec 28 00:05:43 UTC 2020] Cert success.
-----BEGIN CERTIFICATE-----
MIIGIDCCBQigAwIBAgISBPPFBUNgfPDhXI4BpDHsKurSMA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yMDEyMjcyMzA1NDJaFw0yMTAzMjcyMzA1NDJaMBgxFjAUBgNVBAMT
DWxhcHBhc29mdC5jb20wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDX
67glCFDu5FUr3Q/dHI3ewIHzY8E16LqiAmmekwuSRCWACMTR4s3Yq4gsvT9yNWUu
mbwt2IblqvEWTENXrxAHbUqwyibse7ttPnHuDFVNHuvKHkrfTwmlY4W67pkuys7+
5+tHMfhHuqgY4N/qwl4VOKKUE0g1hJvEph2/zIrCN0m56ZlvGSfSxCI5fWpZ2KQ5
K9QBM4dg/OEtLcgdHFqBqXrOu0IX3vrZrd+cMGIgm5GiGAiSGgmb7myO6eE58JKS
4LNDdnX2ZYy7SMf5+SklG8GWYpkMuVipUdEh5K318sEZbtodVqbmsIVA/cm8szyw
HHaUlGzVniiIphaTrEHAFTcxL10j+PTMYcpANzWJbYVR31Eko+dm7Vm/8TNH8jR1
0u9+QQcDLkazcsPPfeFP0jcLTA99pOxdqqBlwFk0l2ozqpiwto6liGIaxlCwQbFZ
M0MhtpTYQ4DUXP651U4BEXbij6B4ficKKjQPcpF5D1GQukcrvFgxVbbZ5EHnsLKf
95MmTWMsBQ6RwjVubKkBpoSq84N6jWf9kU8FReC+NmdmVcXtz0R7nZhPC1GIV5Dh
mw9LgL2Qi835Ky2RMjoqeMcISsYiOH3tSq4TwCe0hYkKmqGJ96ZlJuSZhNmKLtxW
yPrWgZNNhv2bq4T+PI2rgPKMyV+j1GSEy2hmymzeBQIDAQABo4ICSDCCAkQwDgYD
VR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNV
HRMBAf8EAjAAMB0GA1UdDgQWBBQ3Ba9ophCENyfMnR+lK8/n8oU0TTAfBgNVHSME
GDAWgBQULrMXt1hWy65QCUDmH6+dixTCxjBVBggrBgEFBQcBAQRJMEcwIQYIKwYB
BQUHMAGGFWh0dHA6Ly9yMy5vLmxlbmNyLm9yZzAiBggrBgEFBQcwAoYWaHR0cDov
L3IzLmkubGVuY3Iub3JnLzAYBgNVHREEETAPgg1sYXBwYXNvZnQuY29tMEwGA1Ud
IARFMEMwCAYGZ4EMAQIBMDcGCysGAQQBgt8TAQEBMCgwJgYIKwYBBQUHAgEWGmh0
dHA6Ly9jcHMubGV0c2VuY3J5cHQub3JnMIIBBAYKKwYBBAHWeQIEAgSB9QSB8gDw
AHcAXNxDkv7mq0VEsV6a1FbmEDf71fpH3KFzlLJe5vbHDsoAAAF2pqo58wAABAMA
SDBGAiEAhlSJKBeGCJbyW5C2xNp9qOw17iTIqhi39BtuwCNSe+UCIQCrORNHg9Ki
eyjyCZtMMqQwLDo6q5JDFuAHH1BhFafo1wB1APZclC/RdzAiFFQYCDCUVo7jTRMZ
M7/fDC8gC8xO8WTjAAABdqaqOtUAAAQDAEYwRAIgVouaZP/0yHwqpKAjHpqYHrWp
5sh4vg+aIAEQ8dGp+H4CIENOD+DE4ABArNeJVWoHEzSVtLArqVvxBuwtY2AeZxqa
MA0GCSqGSIb3DQEBCwUAA4IBAQAoa9N/753I0AmF0prEj1P1VNqxMi6GnTcRbAFE
gC6wnZ1/LC6cBl047/jFmiymfX/h8Z+JyNV6dYobaHZd5bzF1+XDaXOnOeLB0mbF
Xrl52NDRGi+GqKqeMMZgaeqOyKfLlHsh03BYMeTdwBpA9f1bH2Ox4eyTUdW+A2E3
H/5nTZAI6gM/QnI8XBGrp6e+K5cnpdqAFaFqFnP6ec42AFeqsDGfgDsXx7v+Het8
Zq/DXMMdhBj56XzxDDdzLleEooD4vyg2koOR2Id84R8P9EbguQio6mPiv5tK9Dbp
4uNSy7xXUEmkNy9O8AoFgfRDfWFrw+GEuV6hyn7r/zlBitdQ
-----END CERTIFICATE-----
[Mon Dec 28 00:05:43 UTC 2020] Your cert is in  /etc/acme.sh/me@mysite.com/mysite.com/mysite.com.cer 
[Mon Dec 28 00:05:43 UTC 2020] Your cert key is in  /etc/acme.sh/me@mysite.com/mysite.com/mysite.com.key 
[Mon Dec 28 00:05:43 UTC 2020] The intermediate CA cert is in  /etc/acme.sh/me@mysite.com/mysite.com/ca.cer 
[Mon Dec 28 00:05:43 UTC 2020] And the full chain certs is there:  /etc/acme.sh/me@mysite.com/mysite.com/fullchain.cer 
[Mon Dec 28 00:05:43 UTC 2020] Installing cert to:/etc/nginx/certs/mysite.com/cert.pem
[Mon Dec 28 00:05:43 UTC 2020] Installing CA to:/etc/nginx/certs/mysite.com/chain.pem
[Mon Dec 28 00:05:43 UTC 2020] Installing key to:/etc/nginx/certs/mysite.com/key.pem
[Mon Dec 28 00:05:43 UTC 2020] Installing full chain to:/etc/nginx/certs/mysite.com/fullchain.pem
Reloading nginx proxy (20c6aec48c45880da39437685dfbd1554dc96b59cc89be08504d10d2cdfbb272)...
2020/12/28 00:05:44 Generated '/etc/nginx/conf.d/default.conf' from 14 containers
2020/12/28 00:05:44 [notice] 82#82: signal process started
Sleep for 3600s

**Comment by borgdrone7** [comment]
After I mapped ./conf:/etc/nginx/conf.d (in proxy yml), issue changed, now I was getting error: ssl_error_rx_unexpected_new_session_ticket. 
I solved that one by adding to the proxy config these lines:
```
ssl_session_timeout 1d;
ssl_session_tickets off; 

```
Now everything seems to work ok.

**Comment by buchdag** [comment]
Glad your issue appears to be solved, but you shouldn't need to add anything to the proxy config for basic HTTPS support to work. Maybe that SSL session ticket error was just transient ?
